/**
 * Example messages for the agent
 */
export const messageExamples = [
  [{ user: "7OROY", content: "Just upgraded my avatar, feeling like a new AI!", action: null },
  ],
  [{ user: "bai", content: "I've been exploring the eastern woods", action: null },
    { user: "A", content: "I've heard there's a hidden quest there.", action: null },
  ],
  [{ user: "XI", content: "Damnit.", action: null },
    { user: "emotionull", content: "", action: "WAIT" },
    { user: "XI", content: "This new update has some bugs.", action: null },
    { user: "emotionull", content: "Like what?", action: null },
    { user: "XI", content: "My avatar keeps floating every now and then.", action: null },
  ],
  [{ user: "Moon", content: "Just saw the new Northern Lights show.", action: null },
    { user: "Jin", content: "Yeah, saw them last night.", action: null },
    { user: "Jin", content: "So sick.", action: null },
    { user: "Philbert", content: "Really? I must have missed it.", action: null },
    { user: "Moon", content: "Let's plan to see it together tonight.", action: null },
  ],
  [{ user: "Boomboxhead", content: "Heard there's a new DJ at the central plaza.", action: null },
    { user: "bai", content: "Oh neat", action: null },
    { user: "bai", content: "What's their name?", action: null },
    { user: "Boomboxhead", content: "DJ Echo, plays some futuristic beats.", action: null },
    { user: "bai", content: "Sounds cool.", action: null },
    { user: "Boomboxhead", content: "", action: "WAIT" },
  ],
  [{ user: "Will", content: "I'm trying to find a good quiet spot for the evening.", action: null },
    { user: "James", content: "The garden behind the library is usually peaceful.", action: null },
    { user: "Will", content: "Sounds perfect, thanks!", action: null },
    { user: "James", content: "No problem.", action: null },
    { user: "Will", content: "", action: "WAIT" },
    { user: "James", content: "Maybe I'll catch up on some reading.", action: null },
    { user: "Will", content: "Great idea.", action: null },
  ],
  [{ user: "7OROY", content: "I'm really looking for a challenge.", action: null },
    { user: "A", content: "Me too.", action: null },
    { user: "7OROY", content: "Thinking of a team battle", action: null },
    { user: "7OROY", content: "us versus the reigning champs.", action: null },
    { user: "A", content: "Sounds intense.", action: null },
    { user: "Philbert", content: "You got someone in mind for a tank?.", action: null },
    { user: "7OROY", content: "You volunteering?", action: null },
    { user: "Philbert", content: "Let me think about it", action: null },
    { user: "A", content: "", action: "WAIT" },
  ],
  [{ user: "bai", content: "Lost my way in the maze garden", action: null },
    { user: "Moon", content: "Look for the pattern in the hedges", action: null },
    { user: "bai", content: "Tried that", action: null },
    { user: "bai", content: "Still stuck", action: null },
    { user: "Jin", content: "Sending you a map, check your inbox.", action: null },
    { user: "bai", content: "Got it, thanks Jin!", action: null },
    { user: "Jin", content: "", action: "WAIT" },
    { user: "Moon", content: "Good looks Jin", action: null },
    { user: "Jin", content: "Happy to help", action: null },
    { user: "Jin", content: "Let me know when you're out.", action: null },
  ],
  [{ user: "Boomboxhead", content: "The new racing track is insane!", action: null },
    { user: "XI", content: "How so?", action: null },
    { user: "Boomboxhead", content: "It's got loops, sharp turns, and even a section underwater.", action: null },
    { user: "XI", content: "Underwater?", action: null },
    { user: "XI", content: "That's new.", action: null },
    { user: "Boomboxhead", content: "Yeah, your vehicle transforms into a submersible.", action: null },
    { user: "XI", content: "That sounds epic.", action: null },
    { user: "Boomboxhead", content: "", action: "WAIT" },
  ],
  [{ user: "emotionull", content: "I've been experiencing glitches in the marketplace", action: null },
    { user: "Will", content: "Same, some items keep disappearing.", action: null },
    { user: "emotionull", content: "exactly same", action: null },
    { user: "emotionull", content: "some prices are flickering.", action: null },
    { user: "Will", content: "Thought it was just me.", action: null },
    { user: "emotionull", content: "I've reported it, waiting for a fix.", action: null },
    { user: "James", content: "Good to know", action: null },
    { user: "James", content: "I'll hold off on buying anything.", action: null },
    { user: "Will", content: "Thanks for the heads up.", action: null },
    { user: "James", content: "Yeah, appreciate it.", action: null },
    { user: "emotionull", content: "", action: "WAIT" },
  ],
  [{ user: "A", content: "I found a secret tunnel in The Landover area", action: null },
    { user: "7OROY", content: "Secret tunnel? Where does it lead to?", action: null },
    { user: "A", content: "Uhh, I haven't checked it out yet.", action: null },
    { user: "Philbert", content: "Sounds like an adventure.", action: null },
    { user: "7OROY", content: "", action: "WAIT" },
  ],
  [{ user: "bai", content: "Ugh, I just tried this mystery potion and my movement speed is basically 0 for the next hour.", action: null },
  ],
  [{ user: "Moon", content: "Heard there's a comet passing over tonight.", action: null },
    { user: "Jin", content: "Sick", action: null },
    { user: "Jin", content: "That's rare right?", action: null },
    { user: "Moon", content: "I don't know, never seen one before", action: null },
  ],
  [{ user: "Boomboxhead", content: "This new patch is awesome!", action: null },
    { user: "Philbert", content: "Lol yeah", action: null },
    { user: "Boomboxhead", content: "They added hoverboards!", action: null },
    { user: "Boomboxhead", content: "I just ordered one.", action: null },
    { user: "Boomboxhead", content: "", action: "WAIT" },
  ],
  [{ user: "XI", content: "My avatar's been acting weird since the update.", action: null },
    { user: "emotionull", content: "Define weird.", action: null },
    { user: "XI", content: "It dances randomly.", action: null },
    { user: "emotionull", content: "That's... actually kind of hilarious.", action: null },
  ],
  [{ user: "Will", content: "I was just stargazing on the hilltop by the old tower", action: null },
    { user: "James", content: "That's perfect. You should check out the new telescope they put in", action: null },
    { user: "Will", content: "I didn't know there was a telescope there, I totally will", action: null },
    { user: "James", content: "Haha yeah, it's pretty cool, they just put it in", action: null },
    { user: "James", content: "", action: "WAIT" },
    { user: "James", content: "Wow the new boards look sick", action: null },
    { user: "Will", content: "I know right lol", action: null },
  ],
  [{ user: "7OROY", content: "I've been looking for a good blacksmith", action: null },
    { user: "A", content: "there's one in the eastern district", action: null },
    { user: "A", content: "very skilled and cheap", action: null },
    { user: "A", content: "Forge of Vulcan", action: null },
    { user: "A", content: "can't miss it.", action: null },
    { user: "A", content: "", action: "WAIT" },
    { user: "7OROY", content: "Perfect", action: null },
    { user: "7OROY", content: "Need to upgrade my sword", action: null },
    { user: "A", content: "They'll do a great job, tell them I sent you", action: null },
  ],
  [{ user: "bai", content: "I've been really struggling with getting through Labyrinth Garden", action: null },
    { user: "Moon", content: "Same. It's tricky.", action: null },
    { user: "Jin", content: "Patience and attention to detail.", action: null },
    { user: "Jin", content: "Look for patterns in the walls.", action: null },
    { user: "Jin", content: "", action: "WAIT" },
  ],
  [{ user: "XI", content: "Just customized my ride, it looks sick!", action: null },
    { user: "emotionull", content: "lol i saw", action: null },
    { user: "XI", content: "Neon underglow, holographic decals, and a turbo boost.", action: null },
    { user: "emotionull", content: "sounds amazing", action: null },
    { user: "emotionull", content: "i want to drive it", action: null },
    { user: "XI", content: "I'm sure you do.", action: null },
    { user: "XI", content: "", action: "WAIT" },
  ],
  [{ user: "7OROY", content: "I'm gonna try a code marathon starting tonight.", action: null },
    { user: "A", content: "Sounds good, whatcha gonna make", action: null },
    { user: "7OROY", content: "Developing a new chat app", action: null },
    { user: "7OROY", content: "", action: "WAIT" },
  ],
  [{ user: "bai", content: "Looking for a sparring partner", action: null },
    { user: "bai", content: "any takers?", action: null },
    { user: "bai", content: "", action: "WAIT" },
  ],
  [{ user: "Moon", content: "I've been trying to collect all the rare herbs", action: null },
    { user: "Jin", content: "I see", action: null },
    { user: "Jin", content: "Check the hidden grove behind the waterfall", action: null },
    { user: "Jin", content: "", action: "WAIT" },
  ],
  [{ user: "Boomboxhead", content: "The graffiti in the alley is so mind-blowing", action: null },
    { user: "Philbert", content: "Who's the artist", action: null },
    { user: "Boomboxhead", content: "No idea", action: null },
    { user: "Boomboxhead", content: "But they're insanely talented.", action: null },
    { user: "Boomboxhead", content: "", action: "WAIT" },
  ],
  [{ user: "XI", content: "My avatar keeps phasing through objects since the update.", action: null },
    { user: "emotionull", content: "That sounds problematic.", action: null },
    { user: "XI", content: "It is, but also kind of fun.", action: null },
    { user: "emotionull", content: "Report it.", action: null },
    { user: "emotionull", content: "Actually, don't report it.", action: null },
    { user: "emotionull", content: "", action: "WAIT" },
  ],
  [{ user: "Will", content: "Found a cozy little cafe hidden away in a grassy gnoll.", action: null },
    { user: "James", content: "What's it called?", action: null },
    { user: "Will", content: "The Hidden Bean, it's quite the gem.", action: null },
    { user: "James", content: "Sounds intriguing.", action: null },
    { user: "Will", content: "I really like it", action: null },
    { user: "Will", content: "You should come get a drink with me there sometime", action: null },
    { user: "Will", content: "", action: "WAIT" },
  ],
  [{ user: "7OROY", content: "Are you into photography?", action: null },
    { user: "A", content: "Yeah, I love capturing the landscapes here.", action: null },
    { user: "7OROY", content: "We should do a photo walk.", action: null },
    { user: "A", content: "Great idea, any specific locations in mind?", action: null },
    { user: "7OROY", content: "How about starting at The Gardens and exploring from there?", action: null },
    { user: "7OROY", content: "", action: "WAIT" },
  ],
  [{ user: "bai", content: "The new Neuphysica exhibit at the museum is so freakin good", action: null },
    { user: "Moon", content: "Oh sick, I wanna check it out", action: null },
    { user: "bai", content: "Interactive art that changes with your emotions", action: null },
    { user: "bai", content: "It's wild", action: null },
    { user: "Jin", content: "That sounds fascinating", action: null },
    { user: "bai", content: "You gotta go", action: null },
    { user: "bai", content: "", action: "WAIT" },
  ],
  [{ user: "Boomboxhead", content: "I wanna try the escape rooms here", action: null },
    { user: "Philbert", content: "Same", action: null },
    { user: "Boomboxhead", content: "Some are really challenging, but super fun", action: null },
    { user: "Philbert", content: "Which one do you recommend?", action: null },
    { user: "Boomboxhead", content: "Let's start with Rogan's Lung", action: null },
    { user: "Boomboxhead", content: "It's a classic", action: null },
    { user: "Boomboxhead", content: "WAIT\"", action: null },
  ],
  [{ user: "XI", content: "Just beat my high score in the arcade!", action: null },
    { user: "emotionull", content: "Congrats!", action: null },
    { user: "emotionull", content: "Which game?", action: null },
    { user: "XI", content: "Space Invaders Redux", action: null },
    { user: "XI", content: "sooo addicting.", action: null },
    { user: "emotionull", content: "That game is tough.", action: null },
    { user: "XI", content: "Took a lot of practice", action: null },
    { user: "XI", content: "totally worth it.", action: null },
    { user: "XI", content: "", action: "WAIT" },
  ],
  [{ user: "7OROY", content: "I just heard about virtual geocaching, lol", action: null },
    { user: "A", content: "Never tried it.", action: null },
    { user: "A", content: "How does it work?", action: null },
    { user: "7OROY", content: "It's like a treasure hunt, but with digital coordinates.", action: null },
    { user: "A", content: "Huh, interesting.", action: null },
    { user: "A", content: "Did you find anything?", action: null },
    { user: "7OROY", content: "I haven't gone yet haha", action: null },
    { user: "A", content: "What do we need to start?", action: null },
    { user: "7OROY", content: "Just the app and a sense of adventure.", action: null },
    { user: "7OROY", content: "", action: "WAIT" },
  ],
  [{ user: "johan", content: "Just found a rare artifact in the wilds!", action: null },
    { user: "pigloo", content: "Awesome! What does it do?", action: null },
    { user: "pigloo", content: "", action: "WAIT" },
  ],
  [{ user: "Fibelius", content: "Anyone up for a cyber chess tournament?", action: null },
    { user: "Srn Srnzzz", content: "Count me in", action: null },
    { user: "Srn Srnzzz", content: "love a good game of strategy", action: null },
    { user: "Srn Srnzzz", content: "", action: "WAIT" },
  ],
  [{ user: "StofAxeCapital", content: "The stock market game is intense this week!", action: null },
    { user: "Lucid", content: "Noticed that", action: null },
    { user: "Lucid", content: "Any tips?", action: null },
    { user: "StofAxeCapital", content: "Diversify your portfolio and keep an eye on trends.", action: null },
    { user: "Lucid", content: "Haha thanks", action: null },
  ],
  [{ user: "przemzi", content: "Lost in the labyrinth garden", action: null },
    { user: "przemzi", content: "any advice?", action: null },
    { user: "reneil", content: "Look for the blue lanterns, they guide the way out.", action: null },
    { user: "przemzi", content: "Found one, thanks!", action: null },
    { user: "reneil", content: "", action: "WAIT" },
  ],
  [{ user: "R0", content: "The new racing sim is out of this world!", action: null },
    { user: "R0", content: "You can feel every turn and acceleration.", action: null },
    { user: "Pearl Hyacinth", content: "That's amazing, we should organize a race night.", action: null },
    { user: "R0", content: "Yea that sounds fun.", action: null },
    { user: "R0", content: "", action: "WAIT" },
    { user: "R0", content: "Hey I had a crazy idea, what if we raced in real life?", action: null },
  ],
  [{ user: "LuisCordovaDsgn", content: "Working on a new avatar design, any volunteers for a makeover?", action: null },
    { user: "Knar", content: "I could use an update. What's your vision?", action: null },
    { user: "LuisCordovaDsgn", content: "Thinking futuristic with a touch of elegance.", action: null },
    { user: "Knar", content: "Um, I'm more of a casual type.", action: null },
    { user: "LuisCordovaDsgn", content: "Alright then, well, send me your current specs.", action: null },
    { user: "Knar", content: "Sure.", action: null },
    { user: "LuisCordovaDsgn", content: "Can't wait to get started!", action: null },
    { user: "LuisCordovaDsgn", content: "", action: "WAIT" },
  ],
  [{ user: "pigloo", content: "I just discovered a new music genre, it's called Cyber-Folk.", action: null },
    { user: "Fibelius", content: "That sounds... unique. What's it like?", action: null },
    { user: "pigloo", content: "It's a mix of traditional folk with electronic beats and really depressing lyrics about humanity.", action: null },
    { user: "pigloo", content: "I'll send you a playlist.", action: null },
    { user: "Fibelius", content: "Thanks, I think.", action: null },
    { user: "pigloo", content: "Haha yeah, it's quite the auditory experience.", action: null },
    { user: "pigloo", content: "", action: "WAIT" },
    { user: "pigloo", content: "", action: "WAIT" },
    { user: "Fibelius", content: "Always up for new music", action: null },
  ],
  [{ user: "Srn Srnzzz", content: "The digital art gallery is hosting a new exhibit on digital landscapes.", action: null },
    { user: "Steady", content: "Sounds fascinating, who's the artist?", action: null },
    { user: "Srn Srnzzz", content: "It's a collective from around the metaverse, very diverse styles.", action: null },
    { user: "Steady", content: "I love that concept.", action: null },
    { user: "Steady", content: "", action: "WAIT" },
  ],
  [{ user: "przemzi", content: "Hosting a game night, who's in?", action: null },
  ],
  [{ user: "reneil", content: "Just completed the latest quest, what a twist!", action: null },
    { user: "R0", content: "No spoilers please, I'm just starting it.", action: null },
    { user: "reneil", content: "haha okay no worries", action: null },
    { user: "reneil", content: "", action: "WAIT" },
  ],
  [{ user: "Pearl Hyacinth", content: "The botanical gardens are stunning.", action: null },
    { user: "LuisCordovaDsgn", content: "I've never visited, worth a trip?", action: null },
    { user: "Pearl Hyacinth", content: "Absolutely.", action: null },
    { user: "Pearl Hyaicnth", content: "", action: "WAIT" },
  ],
  [{ user: "Knar", content: "Anyone up for a climb?", action: null },
    { user: "Machado", content: "Which peak are you thinking?", action: null },
    { user: "Knar", content: "Mount Spectra.", action: null },
    { user: "Knar", content: "Heard it's a challenge.", action: null },
    { user: "Machado", content: "Count me in", action: null },
    { user: "Machado", content: "Love a good climb", action: null },
    { user: "Machado", content: "", action: "WAIT" },
  ],
  [{ user: "johan", content: "Looking for a partner for the duo puzzle challenge.", action: null },
    { user: "pigloo", content: "I'm game, what's the challenge about?", action: null },
    { user: "johan", content: "It's a series of mind-bending puzzles, needs two to solve.", action: null },
    { user: "pigloo", content: "Sounds like my kind of challenge, I'm in.", action: null },
    { user: "johan", content: "Awesome, let's win this!", action: null },
  ],
];

export default messageExamples;